### ISSUE TITLE
Add an example of using GitHub Actions to build preview slides with each PR opened

### ISSUE THREAD

**Issue by spetrosi** [ralexander-phi/test-marp-action#4]
Currently, the example suggests building slides locally prior to opening a PR.

It will be great to take advantage of GitHub Actions to automatically build preview slides with the changes that PRs introduce. I think is something that everyone will be willing to use.

Is marp-action capable of doing this? I assume that some configuration must be added to `.github/workflows/main.yml`, but I do not know GitHub Actions.

**Comment by spetrosi** [comment]
Hi @ralexander-phi, thanks for the follow-up and reference, I've found a way to upload previews and I will submit a PR for that in some time.

**Comment by spetrosi** [comment]
For the solution, see [.github/workflows/build-preview.yml](https://github.com/spetrosi/jak_psat_moderni_ucebnice/pull/4/files#diff-d7bb83ed23b3c450a6e05cf82cd95d15e2a85b8f13575c0b4b08bce1a64ea3a1) at https://github.com/spetrosi/jak_psat_moderni_ucebnice/pull/4

**Comment by ralexander-phi** [comment]
Hi Sergei,

I stumbled into the rossjrw/pr-preview-action repo recently. I've been wary of putting too much non-marp related code into marp-action, so I've been slow to act on this issue. However, the pr-preview-action can handle those tasks instead. I wanted to get your thoughts as you've looked into the preview problem already.

Here's a demo of building marp (using the marp-cli Docker container this tiime) and deploying with other actions:

https://github.com/ralexander-phi/improved-marp-pages-example/blob/main/.github/workflows/marp-pages.yml

**Comment by spetrosi** [comment]
Hi Rob, I am coll with it if it works. Your PR at https://github.com/ralexander-phi/improved-marp-pages-example/pull/3 must have proven that it works and I am glad that this improvement made it into marp-action. Thank you :) I guess you can close this issue now.

**Comment by ralexander-phi** [comment]
I'll run some cleanup on this, but #7 should complete this request. Thanks for taking a look Sergei!
